### ISSUE TITLE
Logging all db activities

### ISSUE THREAD

**Issue by morlandi** [CiCiUi/django-db-logger#12]
This is more a question than an issue.
Suppose I needed to log all db activities ... something like:

    LOGGING = {
        ...
        'loggers': {
            ...
            'django.db.backends': {
                'handlers': ['db_log', ],
                'level': 'DEBUG',
            },
            ...
        }
        
Do you have any suggestion on how I could remove the queries due to the django-db-logger module itself, in order to prevent an infinite loop ?

**Comment by patvdleer** [comment]
```python
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "%(levelname)s %(asctime)s %(module)s "
                      "%(process)d %(thread)d %(message)s"
        }
    },
    "handlers": {
        'db_log': {
            'level': 'DEBUG',
            'class': 'django_db_logger.db_log_handler.DatabaseLogHandler'
        },
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        }
    },
    "root": {
        "level": "INFO",
        "handlers": [
            "console",
            "db_log",
        ]
    },
}
```

**Comment by morlandi** [comment]
thank you
