### ISSUE TITLE
Time zone consideration for create_datetime

### ISSUE THREAD

**Issue by maverick42** [CiCiUi/django-db-logger#14]
Hi,

Django Model's DateTimeField is taking UTC 

`create_datetime = models.DateTimeField(auto_now_add=True, verbose_name='Created at')`

So, in admin form,  create_datetime is displayed in UTC format. But I want locale-aware results ... 

`return instance.create_datetime.strftime('%Y-%m-%d %X')`

The %X option simply spit out the full time converted for the locale.

you must convert it before to take into account the time zone as :

`return timezone.localtime(instance.create_datetime)`
or
`return timezone.localtime(instance.create_datetime).strftime('%Y-%m-%d %X')`

Best regards
Frédérik

**Comment by Natgho** [comment]
Added, thanks;
https://github.com/CiCiUi/django-db-logger/commit/6458dfbae3bb5c519a6d04ef558ad7e6939685df
