### ISSUE TITLE
django.utils.encoding.python_2_unicode_compatible() Is Removed in Django 3.0

### ISSUE THREAD

**Issue by nguyenlieunhatvy** [CiCiUi/django-db-logger#15]
I get this error when I try to use django-db-logger with Django 3.0

```bash
*/venv/lib/python3.7/site-packages/django_db_logger/models.py", line 3, in <module>
    from django.utils.encoding import python_2_unicode_compatible
ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding'
```

It is because Django 3.0 has removed Python 2 compatibility APIs as described at http://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis

Remove `python_2_unicode_compatible` inside django-db-logger/models.py does solve the error but I do not know it is a valid fix.

**Comment by donzthefonz** [comment]
Install Six and then replace the 'python_2_unicode_compatible' with 'six'.

So in models:
`from django.utils.encoding import python_2_unicode_compatible
`becomes
`from six import python_2_unicode_compatible
`

**Comment by GitRon** [comment]
Having the same issue

**Comment by GitRon** [comment]
@zhangshine Awesome, thanks! Could you tell me when you plan to release the latest changes to pypi?

**Comment by zhangshine** [comment]
@GitRon I have uploaded a new version to pypi, please check it out

**Comment by GitRon** [comment]
Great! I will! Thanks!

**Comment by GitRon** [comment]
Works for me! Thanks for the super fast merge & publish!
