### ISSUE TITLE
Log request headers, and request and response BODY ?

### ISSUE THREAD

**Issue by dfrankow** [CiCiUi/django-db-logger#22]
Is there a way to also write the request headers, and request and response BODY?

See also [code in django-request-logging](https://github.com/Rhumbix/django-request-logging/blob/master/request_logging/middleware.py).

I looked into hooking this package and django-request-logging together, but I don't yet see how they can fit together.

**Comment by zhangshine** [comment]
Try to low your logging level to `DEBUG` and test it again

**Comment by dfrankow** [comment]
I appreciate your reply. I am still having trouble getting this to work the way I wish.

When I turn up django.request log level in 'loggers' to DEBUG, I think django-request-logging logs the header, but not the body of the POST request or response. It also logs every request, whether HTTP 400-599 or not.

I think the log level in the 'db_log' handler has a similar effect. So:

- I can get request headers, but at the price of lots of verbose non-error logging
- I can't get POST body of request or response

In addition, since there are multiple log lines per request, I tried https://github.com/dabapps/django-log-request-id/ to assign a request id to multiple messages. For some reason, it works on the console, but not in the DB logging.

Getting this to all work together, and in reasonable fashion, is not easy. Perhaps things out of the box don't work the way I'd hope.

Suggestions welcome.

**Comment by zhangshine** [comment]
You can set the default log level of `django-request-logging` to `INFO` or others values you like https://github.com/Rhumbix/django-request-logging#request_logging_data_log_level . 

They only log json response, you can read the code here https://github.com/Rhumbix/django-request-logging#request_logging_data_log_level . Both codebase of `django-db-logger` and `django-request-logging`  are pretty simple and easy to read. Just read the whole code. It won't take long.

**Comment by dfrankow** [comment]
Thanks. Yeah, reading is not the problem, it's understanding how it all fits together and works.
