### ISSUE TITLE
ModuleNotFound Error : django-db-logger

### ISSUE THREAD

**Issue by nikhilchauhankrantitechservices** [CiCiUi/django-db-logger#29]
I am getting this error when i put django-db-logger in INSTALLED_APPS in settings.py file.I am working in virtual environment. i have also installed django-db-logger by : pip install django-db-logger

**Comment by zhangshine** [comment]
Run `pip freeze` to check if you have successfully installed this package. If `django-db-logger` doesn't show in the outputs, try to reactivate your virtual environment and reinstall this package.

**Comment by nikhilchauhankrantitechservices** [comment]
Oh you were right.
now its installed correctly. But it's not logging anything to admin panel even after several request with errors

**Comment by zhangshine** [comment]
`django-db-logger` will not record exceptions automatically.

- To record possible exceptions of your codes,  please reference [Quick start - Step 5](https://github.com/CiCiUi/django-db-logger#quick-start)
- To record 500 errors, add handler to `loggers.django.handlers`, please reference https://docs.djangoproject.com/en/4.0/topics/logging/#configuring-logging

**Comment by nikhilchauhankrantitechservices** [comment]
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
        },
        'simple': {
            'format': '%(levelname)s %(asctime)s %(message)s'
        },
    },
    'handlers': {
        'db_log': {
            'level': 'DEBUG',
            'class': 'django_db_logger.db_log_handler.DatabaseLogHandler'
        },
    },
    'loggers': {
        'db': {
            'handlers': ['db_log'],
            'level': 'DEBUG',
            'propagate': False,
        }
    }
}



I have used this in settings.py. it does not record 500 errors.
can you tell me how to record everything if possible. or how to record 500 errors

**Comment by zhangshine** [comment]
`loggers.django`, not `loggers.db`.
```
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
        },
        'simple': {
            'format': '%(levelname)s %(asctime)s %(message)s'
        },
    },
    'handlers': {
        'db_log': {
            'level': 'DEBUG',
            'class': 'django_db_logger.db_log_handler.DatabaseLogHandler'
        },
    },
    'loggers': {
        'django': {
            'handlers': ['db_log'],
            'level': 'DEBUG',
            'propagate': False,
        }
    }
}
```

**Comment by nikhilchauhankrantitechservices** [comment]
By using loggers.django instead of  loggers.db django server is not starting. django.db starts fine

**Comment by zhangshine** [comment]
Oh, sorry. `django.request` not `django`.

**Comment by nikhilchauhankrantitechservices** [comment]
Thanks its working now. I really appreciate your response.
