### ISSUE TITLE
Can't save logs to database?

### ISSUE THREAD

**Issue by Instrumedley** [CiCiUi/django-db-logger#32]
Found this library to be as simple and minimalist as I needed it to be, but I'm not sure what I'm doing wrong here. After following the installation instructions, I'd expect that doing "db_logger.info" for example would fill in my table django_db_logger_statuslog with data, but it's not the case.

Not sure if I am missing something on the usage or in the way to tell the library to direct the output to the db. Any help?

**Comment by Natgho** [comment]
There is no answer. It seems the problem is solved.
