### ISSUE TITLE
Updated styling for the logs admin

### ISSUE THREAD

**Issue by cuu508** [CiCiUi/django-db-logger#34]
Would there be interest in making some visual changes to the admin list view?

Here's what I've been toying with:

![image](https://github.com/CiCiUi/django-db-logger/assets/661859/71473dbc-9158-4ae3-a2ac-0e5faa0453ba)

* Date column moved to the left, and uses a compact format
* Use a badge with a letter instead of text color to indicate the log level
* Message and traceback shown in the same column. The traceback is hidden by default using the `<details>` and `<summary>` elements

**Comment by zhangshine** [comment]
Looks pretty good, but I don't write Python code anymore. This repository is abandoned.

**Comment by cuu508** [comment]
Ah I see. No worries.

It may be a good idea to add a note in README about the project's status.
