### ISSUE TITLE
django.request

### ISSUE THREAD

**Issue by andreasssm** [CiCiUi/django-db-logger#5]
I want to capture put/get requests, and store in database. That is showing headers and body of request. Is this possible with this tool? If yes, how?

**Comment by jpic** [comment]
Can you describe what you have tried so far ?

I would say, just enable the [logger for django.request](https://docs.djangoproject.com/en/2.1/topics/logging/#django-request)

**Comment by andreasssm** [comment]
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
        },
        'simple': {
            'format': '%(levelname)s %(asctime)s %(message)s'
        },
    },
    'handlers': {
        'db_log': {
            'level': 'DEBUG',
            'class': 'django_db_logger.db_log_handler.DatabaseLogHandler'
        },
    },
    'loggers': {
        'django.request': {
            'handlers': ['db_log'],
            'level': 'DEBUG'
        }
    }
}
I have added the above but it doesnt grab headers and body of request

**Comment by jpic** [comment]
According to the docs, it should at least save the request object in the context. However, the docs do not mention of a capturing of the response, so, you might have to implement your own middleware, if django-db-logger doesn't provide any. Perhaps even, contribute the said middleware to django-db-logger.

**Comment by zhangshine** [comment]
Thanks @jpic . It's a bit hard for me to reply the issue with english 😵

@andreasssm I am sorry this project does not support logging request data😊
