### ISSUE TITLE
Apply/use formatter

### ISSUE THREAD

**Issue by jvlymen** [CiCiUi/django-db-logger#6]
Hi

Like this utility. Very handy for a project that we are working on.

However, there seems to be a minor bugette in that the message is saved to the database without formatting having been applied. It looks as though only  'msg': record.getMessage()' is used to set the database message field as opposed to making use of whichever formatter is supplied.

For example:
if the _fmt of the db handler is set: Handler: <DatabaseLogHandler (DEBUG)> Formatter: %(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(filename)s %(funcName)s %(lineno)d %(message)s. This is not used.

It looks like a one line fix to apply a formatter to the message (if a formatter exists).

If I have misunderstood the code then please let me know.

Many thanks

Joe (jvlymen@pobox.com)

**Comment by Bloodmallet** [comment]
Greetings, 

I was looking for the same thing. So noticing the `options` [branch](https://github.com/CiCiUi/django-db-logger/tree/options) was great. When do you intend to merge it into `master`?
