### ISSUE TITLE
Extending StatusLog

### ISSUE THREAD

**Issue by Bloodmallet** [CiCiUi/django-db-logger#7]
Greetings,

this is an excellent and handy tool. In the spirit of [this pull request](https://github.com/CiCiUi/django-db-logger/pull/3), I was wondering, if it would be feasible to make extending `StatusLog` easier. I'm looking for a way to add some fields to the standard model and to populate them.

Example model:
```python
class MyOwnLog(django_db_logger.StatusLog):
    data1 = models.CharField([...])
    data2 = models.ForeignKey([...], blank=True, null=True)
```

Example use:
```python
db_logger.info("Someone did something", data1, data2)
```

Expected result in admin:

Message | Trace | Create Datetime| Data1 | Data2
--- | --- | --- | --- | ---
Someone did something | | ... | data1 | data2

**Comment by NiMeDia** [comment]
This could also allow to have some "multi instance" logging, which is currently only possible by filtering the log name. But there are use cases where you explicitelly want to separate logs from another.

**Comment by Natgho** [comment]
Outdated.
